### ISSUE TITLE
Turkish language

### ISSUE THREAD

**Issue by Dogacanacc** [KRILLE123/esx-kr-advanced-shops#5]
`Locales['tr'] = {
  ['press_to_open'] = 'Menüyü açmak için ~INPUT_CONTEXT~ tuşuna basın.',
	['press_to_rob'] = '~w~Mağazayı ~r~soymak ~w~için ~INPUT_CONTEXT~ tuşuna basın.',
	['press_to_open_center'] = 'Market menüsünü açmak için ~INPUT_CONTEXT~ tuşuna basın.',
	['name_shop'] = 'Marketine ne isim vermek istersin?',
	['buy_shop'] = 'Marketi satın al ',
	['robbery_cancel'] = '~r~Soygun iptal edildi! (Çok fazla uzaklaştın)',
	['set_price'] = '~g~Satmak istediğiniz ne fiyatı ayarlayın.',
	['how_much'] = '~g~Ne kadar satmak istersiniz?',
}`

**Comment by LySoon** [comment]
@Dogacanacc Thanks for sharing :)
seeing some stuff made by my country's ppl makes me happy
